//! Configuration subcommands (`config init`, `validate`, `show`).
//!
//! `init` writes a profile-based `primusdb.toml`; the other subcommands
//! read and check that file locally (no server round-trip).

use std::path::PathBuf;

use crate::cli::command::{ConfigSubcommands, GlobalArgs};
use crate::cli::output::{format_output, OutputData, OutputFormat};
use crate::Result;

/// Return the default TOML template for the given profile.
fn config_for_profile(profile: &str) -> &'static str {
    match profile {
        "single-node" => {
            r##"# PrimusDB v1.3.1-alpha — Single-node production configuration
# Generated by `primusdb config init --profile single-node`

[storage]
data_dir = "/var/lib/primusdb/data"
max_file_size = 4294967296
compression = "zstd"
cache_size = 1073741824

[network]
bind_address = "0.0.0.0"
port = 8080
max_connections = 2000

[security]
encryption_enabled = true
key_rotation_interval = 86400
auth_required = true

[cluster]
enabled = false
node_id = "prod_node"
discovery_servers = []

[logging]
level = "info"
format = "json"
"##
        }
        "cluster-node" => {
            r##"# PrimusDB v1.3.1-alpha — Cluster node configuration
# Generated by `primusdb config init --profile cluster-node`

[storage]
data_dir = "/var/lib/primusdb/data"
max_file_size = 4294967296
compression = "zstd"
cache_size = 2147483648

[network]
bind_address = "0.0.0.0"
port = 8080
max_connections = 5000

[security]
encryption_enabled = true
key_rotation_interval = 43200
auth_required = true

[cluster]
enabled = true
node_id = "cluster_node_1"
discovery_servers = ["coordinator:8080", "node2:8080"]

[logging]
level = "info"
format = "json"
"##
        }
        "secure" => {
            r##"# PrimusDB v1.3.1-alpha — Secure production configuration
# Generated by `primusdb config init --profile secure`

[storage]
data_dir = "/var/lib/primusdb/data"
max_file_size = 1073741824
compression = "zstd"
cache_size = 536870912

[network]
bind_address = "127.0.0.1"
port = 8080
max_connections = 1000

[security]
encryption_enabled = true
key_rotation_interval = 21600
auth_required = true

[cluster]
enabled = false
node_id = "secure_node"
discovery_servers = []

[logging]
level = "warn"
format = "json"
"##
        }
        "dev" => {
            r##"# PrimusDB v1.3.1-alpha — Development configuration
# Generated by `primusdb config init --profile dev`

[storage]
data_dir = "./dev-data"
max_file_size = 536870912
compression = "lz4"
cache_size = 134217728

[network]
bind_address = "0.0.0.0"
port = 8080
max_connections = 500

[security]
encryption_enabled = false
key_rotation_interval = 86400
auth_required = false

[cluster]
enabled = false
node_id = "dev_node"
discovery_servers = []

[logging]
level = "debug"
format = "text"
"##
        }
        _ => {
            r##"# PrimusDB v1.3.1-alpha — Local development configuration
# Generated by `primusdb config init`

[storage]
data_dir = "./data"
max_file_size = 1073741824
compression = "lz4"
cache_size = 104857600

[network]
bind_address = "127.0.0.1"
port = 8080
max_connections = 1000

[security]
encryption_enabled = true
key_rotation_interval = 86400
auth_required = false

[cluster]
enabled = false
node_id = "local_node"
discovery_servers = []
"##
        }
    }
}

/// Dispatch a `config` subcommand to its handler.
pub async fn handle_config(
    cmd: ConfigSubcommands,
    _global: &GlobalArgs,
    fmt: &OutputFormat,
) -> Result<()> {
    match cmd {
        ConfigSubcommands::Init {
            output,
            force,
            profile,
        } => cmd_init(output, force, &profile, fmt).await,
        ConfigSubcommands::Validate { config } => cmd_validate(config, fmt).await,
        ConfigSubcommands::Show { config } => cmd_show(config, fmt).await,
    }
}

async fn cmd_init(
    output: Option<PathBuf>,
    force: bool,
    profile: &str,
    fmt: &OutputFormat,
) -> Result<()> {
    let path = output.unwrap_or_else(|| PathBuf::from("primusdb.toml"));

    if path.exists() && !force {
        let data = OutputData::Error(format!(
            "{} already exists. Use --force to overwrite.",
            path.display()
        ));
        println!("{}", format_output(&data, *fmt));
        return Ok(());
    }

    let config_toml = config_for_profile(profile);
    tokio::fs::write(&path, config_toml).await?;
    let data = OutputData::Message(format!(
        "Config written to {} (profile: {})",
        path.display(),
        profile
    ));
    println!("{}", format_output(&data, *fmt));
    Ok(())
}

async fn cmd_validate(config: Option<PathBuf>, fmt: &OutputFormat) -> Result<()> {
    let path = config.unwrap_or_else(|| PathBuf::from("primusdb.toml"));

    if !path.exists() {
        let data = OutputData::Error(format!("Config file not found: {}", path.display()));
        println!("{}", format_output(&data, *fmt));
        return Ok(());
    }

    let content = tokio::fs::read_to_string(&path).await?;

    match content.parse::<toml::Value>() {
        Ok(val) => {
            let mut issues: Vec<String> = Vec::new();

            if val.get("storage").is_none() {
                issues.push("Missing [storage] section".into());
            }
            if val.get("network").is_none() {
                issues.push("Missing [network] section".into());
            }
            if val.get("security").is_none() {
                issues.push("Missing [security] section (recommended)".into());
            }

            if issues.is_empty() {
                let data = OutputData::Message(format!("Config is valid: {}", path.display()));
                println!("{}", format_output(&data, *fmt));
            } else {
                let data = OutputData::Table {
                    headers: vec!["Issue".into(), "Detail".into()],
                    rows: issues
                        .into_iter()
                        .map(|i| vec![i, "Recommended".into()])
                        .collect(),
                };
                println!("{}", format_output(&data, *fmt));
            }
        }
        Err(e) => {
            let data = OutputData::Error(format!("Invalid config: {}", e));
            println!("{}", format_output(&data, *fmt));
        }
    }

    Ok(())
}

async fn cmd_show(config: Option<PathBuf>, fmt: &OutputFormat) -> Result<()> {
    let path = config.unwrap_or_else(|| PathBuf::from("primusdb.toml"));

    if !path.exists() {
        let data = OutputData::Error(format!("Config file not found: {}", path.display()));
        println!("{}", format_output(&data, *fmt));
        return Ok(());
    }

    let content = tokio::fs::read_to_string(&path).await?;
    let data = OutputData::Message(content);
    println!("{}", format_output(&data, *fmt));
    Ok(())
}
