#!/usr/bin/env bash
#
# generate-completions.sh — Generate shell completion scripts for PrimusDB
#
# Usage:
#   ./scripts/generate-completions.sh
#   ./scripts/generate-completions.sh --shell bash
#   ./scripts/generate-completions.sh --output ./completions
#
set -euo pipefail

SHELLS=("bash" "zsh" "fish" "powershell" "elvish")
OUTPUT_DIR="./completions"
HELP=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --shell) SHELLS=("$2"); shift 2 ;;
        --output) OUTPUT_DIR="$2"; shift 2 ;;
        --help|-h) HELP=1; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [[ "$HELP" -eq 1 ]]; then
    echo "Usage: $0 [--shell SHELL] [--output DIR]"
    echo "  --shell SHELL     Single shell to generate for (bash/zsh/fish/powershell/elvish)"
    echo "  --output DIR      Output directory (default: ./completions)"
    exit 0
fi

# Ensure the binary exists
if [[ ! -f target/release/primusdb ]] && [[ ! -f target/debug/primusdb ]]; then
    echo "PrimusDB binary not found. Building..."
    cargo build
fi

BINARY="target/debug/primusdb"
if [[ -f target/release/primusdb ]]; then
    BINARY="target/release/primusdb"
fi

mkdir -p "$OUTPUT_DIR"

for shell in "${SHELLS[@]}"; do
    echo "Generating completions for ${shell}..."
    "$BINARY" completion "$shell" > "${OUTPUT_DIR}/primusdb.${shell}" 2>/dev/null || {
        # Fallback: generate with clap if available
        cat > "${OUTPUT_DIR}/primusdb.${shell}" << EOF
# PrimusDB shell completions for ${shell}
# Generated by scripts/generate-completions.sh
# NOTE: Shell completion generation requires the 'clap_complete' crate.
# Install manually or run: primusdb completion <shell>
EOF
    }
    echo "  Wrote ${OUTPUT_DIR}/primusdb.${shell}"
done

echo ""
echo "Completions generated in ${OUTPUT_DIR}/"
echo ""
echo "To use, add to your shell rc file:"
echo "  Bash:   source ${OUTPUT_DIR}/primusdb.bash"
echo "  Zsh:    source ${OUTPUT_DIR}/primusdb.zsh"
echo "  Fish:   source ${OUTPUT_DIR}/primusdb.fish"
